/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as biddingFactorySol from "./BiddingFactory.sol";
export type { biddingFactorySol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Bidding } from "./Bidding";
export type { CompanyContract } from "./CompanyContract";
export type { GovToken } from "./GovToken";
export type { ProposalFactory } from "./ProposalFactory";
export type { ProposalToken } from "./ProposalToken";
export type { RealDigital } from "./RealDigital";
