/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CompanyContractInterface } from "./CompanyContractInterface";
export type { OwnableInterface } from "./OwnableInterface";
export type { ProposalTokenInterface } from "./ProposalTokenInterface";
