/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProposalToken } from "./ProposalToken";
export type { ProposalTokenInterface } from "./ProposalTokenInterface";
