/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ProposalToken__factory } from "./ProposalToken__factory";
export { ProposalTokenInterface__factory } from "./ProposalTokenInterface__factory";
