/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as biddingFactorySol from "./BiddingFactory.sol";
export * as interfaces from "./interfaces";
export { Bidding__factory } from "./Bidding__factory";
export { CompanyContract__factory } from "./CompanyContract__factory";
export { GovToken__factory } from "./GovToken__factory";
export { ProposalFactory__factory } from "./ProposalFactory__factory";
export { ProposalToken__factory } from "./ProposalToken__factory";
export { RealDigital__factory } from "./RealDigital__factory";
