/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CompanyContractInterface__factory } from "./CompanyContractInterface__factory";
export { OwnableInterface__factory } from "./OwnableInterface__factory";
export { ProposalTokenInterface__factory } from "./ProposalTokenInterface__factory";
