/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BiddingFactory } from "../BiddingFactory";
export type { CompanyContract } from "./CompanyContract";
