/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BiddingFactory__factory } from "../BiddingFactory__factory";
export { CompanyContract__factory } from "./CompanyContract__factory";
