/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ProposalFactoryInterface extends Interface {
  getFunction(nameOrSignature: "createProposalToken"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProposalTokenEmmited"): EventFragment;

  encodeFunctionData(
    functionFragment: "createProposalToken",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createProposalToken",
    data: BytesLike
  ): Result;
}

export namespace ProposalTokenEmmitedEvent {
  export type InputTuple = [owner: AddressLike, newContract: AddressLike];
  export type OutputTuple = [owner: string, newContract: string];
  export interface OutputObject {
    owner: string;
    newContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProposalFactory extends BaseContract {
  connect(runner?: ContractRunner | null): ProposalFactory;
  waitForDeployment(): Promise<this>;

  interface: ProposalFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createProposalToken: TypedContractMethod<
    [_value: BigNumberish, _info: string],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createProposalToken"
  ): TypedContractMethod<
    [_value: BigNumberish, _info: string],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "ProposalTokenEmmited"
  ): TypedContractEvent<
    ProposalTokenEmmitedEvent.InputTuple,
    ProposalTokenEmmitedEvent.OutputTuple,
    ProposalTokenEmmitedEvent.OutputObject
  >;

  filters: {
    "ProposalTokenEmmited(address,address)": TypedContractEvent<
      ProposalTokenEmmitedEvent.InputTuple,
      ProposalTokenEmmitedEvent.OutputTuple,
      ProposalTokenEmmitedEvent.OutputObject
    >;
    ProposalTokenEmmited: TypedContractEvent<
      ProposalTokenEmmitedEvent.InputTuple,
      ProposalTokenEmmitedEvent.OutputTuple,
      ProposalTokenEmmitedEvent.OutputObject
    >;
  };
}
